-- AlterEnum: Add new AuditAction values for educator profile, exam type, topic CRUD (idempotent)
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'EDUCATOR_PROFILE_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'EXAMTYPE_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'EXAMTYPE_DELETED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'TOPIC_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'TOPIC_DELETED';
